---
# tasks file for nginx
#apt-get update
-name: apt-get update
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

#install nginx
- name: install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present
    force: yes
  notify:
  - restart nginx

# #copy nginx config using file nginx.conf
- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: 
    - validate nginx
    - restart nginx

#copy file index
- name: copy file index
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
  with-items:
    - { src: index.html, dest: "/var/www/{{ domain01 }}/index.html" }
    - { src: phpinfo.php, dest: "/var/www/{{ domain02 }}/index.php" }
  notify: 
    - restart nginx

#copy vhost template
- name : copy vhost template
  template:
    src: nginx_vhost.j2
    dest: "/etc/nginx/sites-available/{{ item }}"
  with_items:
    - "{{ domain01 }}"
    - "{{ domain02 }}"
  notify: 
    - reload nginx

#enable vhost
- name: enable vhost
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items:
    - "{{ domain01 }}"
    - "{{ domain02 }}"
  notify:
    - reload nginx
