---
# tasks file for nginx
#apt-get update
- name: apt-get update
  become: true
  apt:
    update_cache: yes
    force_apt_get: True
    cache_valid_time: 3600

#install nginx
- name: install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present
    force: yes
  notify:
    - restart nginx

#create folder for web
- name: create folder 
  file:
    path: "/var/www/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ domain01 }}"
    - "{{ domain02 }}"

#copy file index
- name: copy file index
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
  with_items:
    - { src: index.html, dest: "/var/www/{{ domain01 }}/index.html" }
    - { src: info.php, dest: "/var/www/{{ domain02 }}/info.php" }

#copy vhost template
- name : create file vhost
  template:
    src: nginx_vhost.j2
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
  with_items:
    - "{{ domain01 }}"
    - "{{ domain02 }}"
  vars:
    domain_name: "{{ item }}"
  notify: 
    - validate nginx
    - restart nginx