---
- name: Ansible Init EC2
  hosts: localhost
  tasks:
#  - name: launching AWS instance using Ansible
#    ec2:
#      key_name: ttt_dev_03
#      group: webserver
#      instance_type: t3a.micro
#      image: ami-0950bf7d28f290092
#      wait: yes
#      wait_timeout: 500
#      volumes:
#        - device_name: /dev/xvda
#          volume_type: gp2
#          volume_size: 8
#      vpc_subnet_id: subnet-88941fd1
#      assign_public_ip: yes
#      count_tag:
#        Name: ubuntu-machine
#      exact_count: 1

  - name: start multiple instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      key_name: ttt_dev_03
      image_id: ami-0950bf7d28f290092
      exact_count: 2
      region: ap-southeast-1
      vpc_subnet_id: subnet-88941fd1
      network:
        assign_public_ip: true
        security_group: default
      tags:
        Name: be
        Environment: nightly
