---
- hosts: be_api
  gather_facts: yes
  become: yes
  vars:
    dir_name: demo-01
    create_file: true
  tasks:
  - name: 'check status'
    shell: 'whoami'
  - name: 'import task file'
    import_tasks: create_dir.yaml
  - name: 'create dir'
    file:
      path: /tmp/{{ dir_name }}
      state: directory
      mode: '0755'
    vars:
      dir_name: demo_02
    tags:
      - create_dir_and_create_file
  - name: 'create files'
    file:
      path: /tmp/{{ dir_name }}/{{ item }}
      state: touch
    loop:
      - test_1.txt
      - test_2.txt
      - test_3.txt
      - test_4.txt
    when: ( create_file is true and dir_name is defined )
    vars:
      dir_name: demo_02
    tags:
      - create_dir_and_create_file

    # with_items:
    #   - test_1.txt
    #   - test_2.txt
    #   - test_3.txt

  - name: 'check dir'
    shell: 'cd /tmp/demo_02 && ls -lart'
    # command: 'ls -lart'
    # become_user: 'ubuntu'
    # tags: ['always']
  - name: 'Copy file to remote hosts'
    copy:
      src: ./{{ item }}
      dest: /tmp/{{ dir_name }}/{{ item }}
      owner: root
      group: root
      mode: '0644'
    with_items:
      - example.yaml
    tags:
      - copy_file
  - name: 'Templating File'
    template:
      src: ./{{ item }}
      dest: /tmp/{{ dir_name }}/{{ item }}
    with_items:
      - template_content.txt.j2
    tags:
      - sync_file
  - name: 'cat sync file'
    shell: 'cat /tmp/demo-01/template_content.txt.j2'
    tags:
      - sync_file
# ######
#   - name: 'change file'
#   - name: 'test'
#     shell: 'run test option1'
#   - name: 'restart'
#     shell: 'service restart'
#   - name: 'update file'
#   - name: 'test'
#     shell: 'run test option1'
#   - name: 'restart'
#     shell: 'service restart'
#   - name: 'copy change file'
#   - name: 'test'
#     shell: 'run test option1'
#   - name: 'restart'
#     shell: 'service restart'

# ####
# tasks:
#   - name: 'execute command 1'
#   - name: 'change file'
#     notify:
#       - test and restart
#       # - test
#       # - restart
# handlers:
#   - name: 'test'
#     shell: 'run test option2 option3'
#     listen: 'test and restart'
#   - name: 'restart'
#     shell: 'service restart'
#     listen: 'test and restart'
