---
- name: remove sites-available and sites-enabled
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
  ignore_errors: true

- name: copy file
  copy:
    src: abc.txt
    dest: /var/www/

- name: override file nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
- name: configure external vhosts
  copy:
    src: web01.conf
    dest: /etc/nginx/conf.d
  when: force_use_external_vhost
  notify:
    - validate nginx
    - reload nginx
