---
- hosts: be_api[0-1]
  gather_facts: yes
  become: yes
  vars:
    dir_name: demo-01
  tasks:
  - name: 'check status'
    shell: 'whoami'
  - name: 'create dir'
    ansible.builtin.shell: mkdir /tmp/{{ dir_name }}
    become_user: 'ubuntu'
    vars:
      dir_name: demo-02
    ignore_errors: true
  - name: 'check dir'
    # command: 'cd /tmp && ls -lart'
    command: 'ls -lart'
    # become_user: 'ubuntu'
    # tags: ['always']
