---
# tasks set up
- name: set up nginx
  ansible.builtin.apt:
    name: nginx
    state: present

# tasks config file
- name: config file 
  copy:
    src: nginx.cfg
    dest: /etc/nginx/nginx.cfg
  notify: 
    - check config nginx
    - Restart nginx

# tasks config file vhost
- name : Template file
  template:
    src: template_nginx.txt.j2
    dest: /etc/nginx/sites-available/{{ host_name }}_template_nginx.conf
  notify: 
    - check config nginx
    - Restart nginx